[build]
builder = "nixpacks"

[deploy]
startCommand = "python manage.py migrate && gunicorn nutri_backend.wsgi --bind 0.0.0.0:$PORT"
healthcheckPath = "/"
healthcheckTimeout = 30
restartPolicyType = "on_failure"