# Generated by Django 6.0.4 on 2026-04-25 13:29

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutrition', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meal',
            name='date',
        ),
        migrations.AddField(
            model_name='meal',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='meal',
            name='meal_type',
            field=models.CharField(choices=[('breakfast', 'Breakfast'), ('lunch', 'Lunch'), ('dinner', 'Dinner'), ('snack', 'Snack')], default='breakfast', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='meal',
            name='quantity',
            field=models.FloatField(default=1),
        ),
        migrations.AlterField(
            model_name='meal',
            name='calories',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='meal',
            name='food_name',
            field=models.CharField(max_length=100),
        ),
    ]
