# Generated by Django 6.0.4 on 2026-05-02 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutrition', '0003_macrotarget'),
    ]

    operations = [
        migrations.RenameField(
            model_name='meal',
            old_name='fat',
            new_name='fats',
        ),
        migrations.AlterField(
            model_name='meal',
            name='meal_type',
            field=models.CharField(choices=[('breakfast', 'Breakfast'), ('lunch', 'Lunch'), ('dinner', 'Dinner'), ('snack', 'Snack')], default='snack', max_length=20),
        ),
    ]
